"""Import the 14 DEBUG website screenshots without changing App Store sources."""

import argparse
import json
import os
from pathlib import Path
from shutil import copyfile
from tempfile import TemporaryDirectory

from PIL import Image, ImageOps


PAGES = {
    "hourly": "Hourly",
    "daily": "10_Days",
    "light": "Light",
    "wind": "Wind",
    "air": "Air",
    "pressure": "Pressure",
    "places": "Places",
}
APPEARANCES = ("dark", "light")


def import_screenshots(source, root):
    files = {path.name.lower(): path for path in source.iterdir() if path.is_file()}
    expected = {
        (page, appearance): f"EN_US_Web_{name}_{appearance.title()}.png"
        for page, name in PAGES.items()
        for appearance in APPEARANCES
    }
    missing = [name for name in expected.values() if name.lower() not in files]
    if missing:
        raise ValueError("Missing screenshots:\n" + "\n".join(missing))

    catalog = {page: {} for page in PAGES}
    assets = root / "images" / "viento"
    scripts = root / "assets" / "js"
    # Validate and convert the complete batch before replacing any website asset.
    with TemporaryDirectory(prefix="viento-web-") as temporary:
        staging = Path(temporary)
        for (page, appearance), name in expected.items():
            with Image.open(files[name.lower()]) as opened:
                original = ImageOps.exif_transpose(opened)
                if original.size != (1206, 2622):
                    raise ValueError(f"{name}: expected 1206 x 2622, got {original.size}")
                original = original.convert("RGB")
                stem = f"{page}-{appearance}"
                catalog[page][appearance] = stem
                for width in (480, 800):
                    size = (width, round(original.height * width / original.width))
                    resized = original.resize(size, Image.Resampling.LANCZOS)
                    resized.save(staging / f"{stem}-{width}.webp", "WEBP", quality=92, method=6)

        # Static HTML also starts dark, including the hero, even without JavaScript.
        for page in ("daily", "places"):
            for width in (480, 800):
                copyfile(staging / f"{page}-dark-{width}.webp", staging / f"{page}-{width}.webp")
        assets.mkdir(parents=True, exist_ok=True)
        scripts.mkdir(parents=True, exist_ok=True)
        for path in staging.glob("*.webp"):
            temporary_asset = assets / f".{path.name}.tmp"
            copyfile(path, temporary_asset)
            os.replace(temporary_asset, assets / path.name)
        manifest = scripts / "viento-previews.js"
        temporary_manifest = scripts / ".viento-previews.js.tmp"
        temporary_manifest.write_text(
            "// Generated by scripts/import-viento-website-screenshots.py\n"
            + "window.VientoPreviewAssets = " + json.dumps(catalog, indent=2) + ";\n",
            encoding="utf-8",
        )
        os.replace(temporary_manifest, manifest)
    return len(expected)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Folder containing EN_US_Web_*.png exports")
    args = parser.parse_args()
    try:
        count = import_screenshots(args.source, Path(__file__).resolve().parents[1])
    except (OSError, ValueError) as error:
        parser.exit(1, f"{error}\n")
    print(f"Imported {count} screenshots. Dark defaults and both appearance toggles are ready.")


if __name__ == "__main__":
    main()
