/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/admin-auth/wrangler.jsonc --include-runtime=false cloudflare/admin-auth/worker-configuration.d.ts` (hash: 57068e9b7c7c1c38530d7a99899dfe95)
interface __BaseEnv_Env {
	ADMIN_BASIC_AUTH_SHA256: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_BASIC_AUTH_SHA256">> {}
}
